# cxxopts library
# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "cxxopts",
    srcs = ["cxxopts.hpp"],
    hdrs = ["cxxopts.hpp"],
    visibility = ["//visibility:public"],
)

# loguru loggin library
cc_library(
    name = "loguru",
    srcs = ["loguru.cpp"],
    hdrs = ["loguru.hpp"],
    visibility = ["//visibility:public"],
)